#!/usr/bin/env bash
# This script loops 10 times, printing Best School, and adds a Hi on the 9th loop
i=1
while [ $i -le 10 ]
do
    echo "Best School"
    if [ $i -eq 9 ]
    then
        echo "Hi"
    fi
    i=$((i + 1))
done
