#!/usr/bin/env bash
# This script loops from 1 to 10 with country-specific superstition checks
i=1
while [ $i -le 10 ]
do
    if [ $i -eq 4 ]
    then
        echo "bad luck from China"
    elif [ $i -eq 8 ]
    then
        echo "good luck from Japan"
    elif [ $i -eq 9 ]
    then
        echo "bad luck from Italy"
    else
        echo "Best School"
    fi
    i=$((i + 1))
done
